name: Hello World

on:
  push:
    branches:
      - '*' #This will trigger on all branches

jobs:
  print-hello-world:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Print Hello World with branch information
      run: |
        echo "Hello World! ${{ github.actor }} just pushed to the ${{ github.ref }} branch within the ${{ github.repository }} repository."
